Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jett-demo-bucket12345
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-047126e50991d067b
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-05f242e036899155f
          GroupSet:
            - sg-0b1d656417e9be564